server:
  port: ${SERVER_PORT:9003}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:Certification}

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:user}
      password: ${SPRING_SECURITY_USER_PASSWORD:user}
      roles: USER

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource-users:
    driver-class-name: org.postgresql.Driver
    url: ${USER_READER_DB_URL:jdbc:postgresql://localhost:5432/users}
    username: ${USER_READER_DB_USERNAME:postgres}
    password: ${USER_READER_DB_PASSWORD:1904}

  datasource-resources:
    driver-class-name: org.postgresql.Driver
    url: ${RESOURCE_DB_URL:jdbc:postgresql://localhost:5432/resources}
    username: ${RESOURCE_DB_USERNAME:resources}
    password: ${RESOURCE_DB_PASSWORD:1904}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:3}
    password: ${REDIS_PASSWORD:1904}

  redis-users:
    host: ${REDIS_HOST_INFRASTRUCTURE:localhost}
    port: ${REDIS_PORT_INFRASTRUCTURE:6379}
    database: ${REDIS_DATABASE_INFRASTRUCTURE:0}
    password: ${REDIS_PASSWORD_INFRASTRUCTURE:1904}

  flyway-resources:
    url: ${RESOURCE_DB_URL:jdbc:postgresql://localhost:5432/resources}
    user: ${RESOURCE_DB_USERNAME:resources}
    password: ${RESOURCE_DB_PASSWORD:1904}
    locations: classpath:migrations/resources
    out-of-order: true
    baseline-on-migrate: true
    enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: id
    consumer:
      group-id: id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL:http://${SPRING_SECURITY_USER_NAME:user}:${SPRING_SECURITY_USER_PASSWORD:user}@localhost:8889/management}
        username: ${SPRING_SECURITY_USER_NAME:user}
        password: ${SPRING_SECURITY_USER_PASSWORD:user}

eureka:
  instance:
    instance-id: ${EUREKA_INSTANCE_ID:${spring.application.name:Certification}:${server.port}}
    hostname: ${EUREKA_HOSTNAME:localhost}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 7
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://${SPRING_SECURITY_USER_NAME:user}:${SPRING_SECURITY_USER_PASSWORD:user}@localhost:8889/eureka}

logging:
  level:
    io.management: DEBUG
    org.apache.kafka.clients: ERROR
    com.netflix.discovery: ERROR
    root: INFO

api:
  resources:
    images:
      size: ${CLOUDINARY_FILES_SIZE_LIMIT:25}
      host: ${CLOUDINARY_HOST:https://api.cloudinary.com/v1_1/dqjeb0ob2/image}
      key: ${CLOUDINARY_KEY:474919738819372}
      secret: ${CLOUDINARY_SECRET:SlJA8pvuSIgcPX1CoAagGE-qWyE}

management:
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
  endpoints:
    web:
      exposure:
        include: '*'