server:
  port: 9003

spring:
  application:
    name: certification

  datasource-users:
    driver-class-name: org.postgresql.Driver
    url: ${USER_READER_DB_URL}
    username: ${USER_READER_DB_USERNAME:postgres}
    password: ${USER_READER_DB_PASSWORD:1904}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:3}
    password: ${REDIS_PASSWORD:1904}

  redis-users:
    host: ${REDIS_HOST_INFRASTRUCTURE:localhost}
    port: ${REDIS_PORT_INFRASTRUCTURE:6379}
    database: ${REDIS_DATABASE_INFRASTRUCTURE:0}
    password: ${REDIS_PASSWORD_INFRASTRUCTURE:1904}

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: id
    consumer:
      group-id: id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

eureka:
  instance:
    instance-id: ${EUREKA_INSTANCE_ID:${spring.application.name}:${server.port}}
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://${SPRING_SECURITY_USER_NAME:user}:${SPRING_SECURITY_USER_PASSWORD:user}@localhost:8889/eureka}

logging:
  level:
    org.apache.kafka.clients: ERROR