server:
  port: 9005

spring:
  application:
    name: message

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource-users:
    driver-class-name: org.postgresql.Driver
    url: ${USER_READER_DB_URL}
    username: ${USER_READER_DB_USERNAME:postgres}
    password: ${USER_READER_DB_PASSWORD:1904}

  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:1}
    password: ${REDIS_PASSWORD:1904}

  redis-users:
    host: ${REDIS_HOST_INFRASTRUCTURE:localhost}
    port: ${REDIS_PORT_INFRASTRUCTURE:6379}
    database: ${REDIS_DATABASE_INFRASTRUCTURE:0}
    password: ${REDIS_PASSWORD_INFRASTRUCTURE:1904}

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: id
    consumer:
      group-id: id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: ${MAIL_ADDRESS}
    password: ${MAIL_ACCESS_TOKEN}
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          starttls.enable: true
          starttls.required: true
          auth: true
          ssl.trust: smtp.gmail.com

eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://${SPRING_SECURITY_USER_NAME:user}:${SPRING_SECURITY_USER_PASSWORD:user}@localhost:8888/eureka}

logging:
  level:
    org.apache.kafka.clients: ERROR