server:
  port: 9093

spring:
  application:
    name: service

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: id
    consumer:
      group-id: id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

logging:
  level:
    org.apache.kafka.clients: ERROR

api:
  shipper:
    np:
      token: 07e4a86cc0f63f9ee4867b58c2034c5b
      host: https://api.novaposhta.ua/v2.0/json/