server:
  port: 9001

spring:
  application:
    name: user

  profiles:
    active: default, native, dev

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

    database-platform: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1904}

  flyway:
    url: ${DB_URL}
    user: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:1904}
    locations: classpath:migration
    out-of-order: true
    baseline-on-migrate: true
    enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      client-id: id
    consumer:
      group-id: id
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

logging:
  level:
    org.apache.kafka.clients: ERROR