version: '3.7'

networks:
  crm:
    external: true

services:
  setting:
    image: setting:latest
    container_name: settings
    ports:
      - "8888:8888"
    environment:
      - CONFIG_SERVER_LOGIN=user
      - CONFIG_SERVER_PASSWORD=user
      - SPRING_PROFILES_ACTIVE=default,native,dev,elk
    networks:
      - crm