version: '3.7'

networks:
  crm:
    external: true

services:
  setting:
    image: setting:latest
    container_name: settings
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=default,native,dev,elk
      - SPRING_SECURITY_USER_NAME=user
      - SPRING_SECURITY_USER_PASSWORD=user
      - ENCRYPT_KEY=keyshot
      - EUREKA_CLIENT_SERVICE_URL=http://user:user@discovery:8889/eureka
      - EUREKA_INSTANCE_ID=Setting:8888
      - EUREKA_HOSTNAME=host.docker.internal
      - LOGSTASH_URL=logstash:5000
    networks:
      - crm