version: '3.7'

networks:
  crm:
    external: true

services:
  setting:
    image: setting:latest
    container_name: settings
    ports:
      - "8888:8888"
    environment:
      - SERVER_PORT=8888
      - SPRING_PROFILES_ACTIVE=default,native,dev,elk
      - ENCRYPT_KEY=keyshot
      - EUREKA_CLIENT_SERVICE_URL=http://user:user@discovery:8889/eureka
      - EUREKA_INSTANCE_ID=Setting:8888
      - EUREKA_HOSTNAME=host.docker.internal
      - LOGSTASH_URL=logstash:5000
      - SPRING_BOOT_ADMIN_CLIENT_URL=http://user:user@discovery:8889/management
    networks:
      - crm