server:
  port: ${SERVER_PORT:8888}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:Setting}

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default, native, dev}

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:user}
      password: ${SPRING_SECURITY_USER_PASSWORD:user}

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/properties

  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL:http://${SPRING_SECURITY_USER_NAME:user}:${SPRING_SECURITY_USER_PASSWORD:user}@localhost:8889/management}
        username: ${SPRING_SECURITY_USER_NAME:user}
        password: ${SPRING_SECURITY_USER_PASSWORD:user}
        instance:
          service-base-url: http://host.docker.internal:${server.port}

encrypt:
  key: ${ENCRYPT_KEY:key}

eureka:
  instance:
    instance-id: ${EUREKA_INSTANCE_ID:${spring.application.name:Setting}:${server.port}}
    hostname: ${EUREKA_HOSTNAME:localhost}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 7
  client:
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://${SPRING_SECURITY_USER_NAME:user}:${SPRING_SECURITY_USER_PASSWORD:user}@localhost:8889/eureka}

management:
  endpoint:
    health:
      show-details: WHEN_AUTHORIZED
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    io.management.ua: DEBUG
    root: INFO
