server:
  port: 8888
spring:
  profiles:
    active: default, native, dev
  security:
    user:
      name: ${CONFIG_SERVER_LOGIN:user}
      password: ${CONFIG_SERVER_PASSWORD:user}
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/properties
