server:
  port: 8888

spring:
  application:
    name: setting

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default, native, dev}

  security:
    user:
      name: ${CONFIG_SERVER_LOGIN:user}
      password: ${CONFIG_SERVER_PASSWORD:user}

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/properties
        prefix: /cloud

encrypt:
  key: dnjjdn38389mMKMDmdkmkdemk4fdm

eureka:
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://user:user@localhost:8888/eureka