server:
  port: 8888

spring:
  application:
    name: setting

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default, native, dev}

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:user}
      password: ${SPRING_SECURITY_USER_PASSWORD:user}

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/properties

encrypt:
  key: ${ENCRYPT_KEY:key}

eureka:
  instance:
    instance-id: ${EUREKA_INSTANCE_ID:localhost:${server.port}}
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    healthcheck:
      enabled: true
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://${SPRING_SECURITY_USER_NAME:user}:${SPRING_SECURITY_USER_PASSWORD:user}@localhost:8889/eureka}

management:
  endpoint:
    health:
      enabled: true
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: "*"