server:
  port: 8888

spring:
  application:
    name: setting

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default, native, dev}

  security:
    user:
      name: ${CONFIG_SERVER_LOGIN:user}
      password: ${CONFIG_SERVER_PASSWORD:user}

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/properties
        prefix: ${SPRING_CLOUD_CONTEXT_PREFIX:/cloud}

encrypt:
  key: ${SPRING_CLOUD_CIPHER_KEY:key}

eureka:
  client:
    registry-fetch-interval-seconds: 5
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://${EUREKA_SERVER_LOGIN:user}:${EUREKA_SERVER_PASSWORD:user}@localhost:8888/eureka}